### ISSUE TITLE
slam networks display not working

### ISSUE THREAD

**Issue by guillaume-philippon** [guillaume-philippon/slam-v2-cli#1]
SlamAPIController doesn't have list method

slam networks display cloud-vd 134.158.74.180                           
Traceback (most recent call last):
  File "/Users/sinese/Code/github/guillaume-philippon/slam-v2-cli/slam", line 63, in <module>
    ctrl.display(args.options())
  File "/Users/sinese/Code/github/guillaume-philippon/slam-v2-cli/networks/controller.py", line 145, in display
    result = self.api.list('networks', options.network, field=feature_uri)
AttributeError: 'SlamAPIController' object has no attribute 'list'

**Comment by guillaume-philippon** [comment]
Fixed by PR #2
